/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../../../index.js";

export interface DeleteAgentAssetDeveloperResponse extends Sonyk.SuccessResponse {
    data?: DeleteAgentAssetDeveloperResponse.Data;
}

export namespace DeleteAgentAssetDeveloperResponse {
    export interface Data {
        /** ID of the deleted asset */
        assetId?: number;
        /** Number of text chunks removed from search database */
        chunksRemoved?: number;
    }
}
