/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../../../index.js";

export interface GetAgentAssetContentDeveloperResponse extends Sonyk.BaseResponse {
    data?: GetAgentAssetContentDeveloperResponse.Data;
}

export namespace GetAgentAssetContentDeveloperResponse {
    export interface Data {
        /** Asset identifier */
        assetId?: number;
        /** Asset title */
        title?: string;
        /** Type of asset */
        type?: Data.Type;
        /**
         * The complete text content of the asset.
         *
         * For FILE assets: Clean, processed text extracted from uploaded files
         * For TEXT assets: Original text content as provided
         * For TRAINING assets: Combined question and answer content
         */
        content?: string;
        /** Length of the content in characters */
        contentLength?: number;
        /** When the asset was originally created */
        dateCreated?: string;
        /** When the asset was last updated */
        lastModified?: string;
    }

    export namespace Data {
        /**
         * Type of asset
         */
        export type Type = "FILE" | "TEXT" | "TRAINING";
        export const Type = {
            File: "FILE",
            Text: "TEXT",
            Training: "TRAINING",
        } as const;
    }
}
