/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sonyk from "../../../index.js";

export interface UpdateAgentAssetDeveloperResponse extends Sonyk.BaseResponse {
    data?: UpdateAgentAssetDeveloperResponse.Data;
}

export namespace UpdateAgentAssetDeveloperResponse {
    export interface Data {
        /** Number of new chunks created (if text was updated) */
        chunkCount?: number;
    }
}
