/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         toolId: "toolId"
 *     }
 */
export interface UnassignToolFromAgentDeveloperRequest {
    toolId: string;
}
