/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         agentId: "68572764-2437-42ce-a5ce-02451e9df97c",
 *         toNumber: "+919831222222"
 *     }
 */
export interface InitiateCallRequest {
    /** UUID of the agent to use for the call */
    agentId: string;
    /** Phone number to call (E.164 format) */
    toNumber: string;
    /** Optional JSON object containing custom variables to pass to the agent during the call */
    variables?: Record<string, unknown>;
}
